
#ifndef ACTIONS_H
#define ACTIONS_H value

#include <SDL.h>

typedef enum {
  TRACKER_STATE_NONE = -1,
  TRACKER_EDIT_SONG = 1,
  TRACKER_EDIT_PATTERN = 2,
  TRACKER_EDIT_INSTRUMENT = 4,
  TRACKER_EDIT_TABLE = 8,
  TRACKER_EDIT_META_DATA = 16,
  TRACKER_EDIT_ANY =
  TRACKER_EDIT_SONG | TRACKER_EDIT_PATTERN | TRACKER_EDIT_INSTRUMENT | TRACKER_EDIT_TABLE | TRACKER_EDIT_META_DATA,
  TRACKER_NONE = 0,
  TRACKER_ANY = TRACKER_EDIT_ANY
} TrackerState;

typedef enum {
  ACTION_NONE = -1,
  ACTION_MOVE_LEFT = 0,
  ACTION_MOVE_RIGHT,
  ACTION_MOVE_UP,
  ACTION_MOVE_DOWN,
  ACTION_NEXT_SECTION,
  ACTION_PREV_SECTION,
  ACTION_NEXT_CHANNEL,
  ACTION_PREV_CHANNEL,
  ACTION_PLAY_STOP_SONG,
  ACTION_NEXT_INSTRUMENT_PARAM,
  ACTION_PREV_INSTRUMENT_PARAM,
  ACTION_WAV_EXPORT,
  ACTION_SAVE,
  ACTION_NEXT_INSTRUMENT,
  ACTION_PREV_INSTRUMENT,
  ACTION_INSERT,
  ACTION_ADD,
  ACTION_DELETE,
  ACTION_CLEAR,
  ACTION_NEXT_OCTAVE,
  ACTION_PREV_OCTAVE,
  ACTION_NEXT_PATTERN,
  ACTION_PREV_PATTERN,
  ACTION_TOGGLE_EDIT,
  ACTION_SWAP_UP,
  ACTION_SWAP_DOWN,
  ACTION_JUMP,
  ACTION_NEXT_TABLE_KIND,
  ACTION_PREV_TABLE_KIND,
  ACTION_NEXT_TABLE,
  ACTION_PREV_TABLE,
  ACTION_NEXT_TABLE_COLUMN,
  ACTION_PREV_TABLE_COLUMN,
  ACTION_SHOW_KEYS,
} Action;

extern char *actionNames[];

typedef struct {
  Action action;
  TrackerState trackerState;
  SDL_Scancode scancode;
  SDL_Keymod modifiers;
} ActionTableEntry;

extern ActionTableEntry actions[];
extern size_t actionsCount;

#endif // ifndef ACTIONS_H

